rabbitmq-service:
  image: "rabbitmq:3-management" 
  environment: 
    RABBITMQ_DEFAULT_USER: "admin"
    RABBITMQ_DEFAULT_PASS: "admin"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672" 
  volumes:
    - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"